server:
  port: 8080

keycloak:
  realm: javapuzzle
  auth-server-url: http://localhost:8085
  resource: my_client
  public-client: true
  bearer-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db?allowPublicKeyRetrieval=true&useSSL=false
    username: sbsst
    password: sbs123414
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
